### ISSUE TITLE
Catch error for no weights

### ISSUE THREAD

**Issue by HENDRIX-ZT2** [OpenNaja/cobra-blender#18]
This is probably when the first vertex has no weight assigned to it.

Traceback (most recent call last):
  File "C:\Users\warri\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\cobra-blender\export_mdl2.py", line 175, in save
    v_index = dummy_vertices[dummy]
KeyError: b'g\xed\xae>\x00tX>x\x0c\x87\xbew\xa3\xef>/\xc3\x7f?w\xa3\xef>/\xc3\x7f?\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x80\xbf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\warri\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\cobra-blender\__init__.py", line 84, in execute
    errors = export_mdl2.save(self, context, **keywords)
  File "C:\Users\warri\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\cobra-blender\export_mdl2.py", line 235, in save
    verts.append((position, residue, normal, unk_0, tangent, bone_index, uvs, vcols, bone_ids, bone_weights, fur_length))
UnboundLocalError: local variable 'bone_index' referenced before assignment

location: <unknown location>:-1

**Comment by HENDRIX-ZT2** [comment]
This is where bone_index ends up being not defined for the first iteration since it is not declared outside of the loop:
https://github.com/OpenNaja/cobra-blender/blob/master/export_mdl2.py#L235

**Comment by HENDRIX-ZT2** [comment]
Actually, unindenting `bone_index = w_s[0][0]` out of the if statement could also do the trick, but needs testing:
https://github.com/OpenNaja/cobra-blender/blob/master/export_mdl2.py#L222
