### ISSUE TITLE
blender errors please help

### ISSUE THREAD

**Issue by james-creator** [OpenNaja/cobra-blender#22]
I've installed pyffi and blender 2.79 works perfectly with mdl2 imports exports. however i can't get blender 2.82 to work correctly, I've tried installing pyffi per the instructions and it says requirement already satisfied. but i get this error (see linked image) when i import mdl2's in blender 2.82

https://imgur.com/a/BMJcnQB

Thanks in advance!

**Comment by HENDRIX-ZT2** [comment]
Latest release of tools and plugin? Confirm, then paste complete console log.

**Comment by james-creator** [comment]
> Latest release of tools and plugin? Confirm, then paste complete console log.

both newest releases.

really appreciate the help. if it helps any the model does import but i only get 1 model and armature, the LOD models are missing.

log:
Traceback (most recent call last):
  File "C:\Users\TCclr\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\cobra-blender\__init__.py", line 70, in execute
    errors = import_mdl2.load(self, context, **keywords)
  File "C:\Users\TCclr\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\cobra-blender\import_mdl2.py", line 395, in load
    mat = create_material(in_dir, model.material)
  File "C:\Users\TCclr\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\cobra-blender\import_mdl2.py", line 216, in create_material
    fgm_data = get_data(fgm_path, FgmFormat.Data)
  File "C:\Users\TCclr\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\cobra-blender\import_mdl2.py", line 19, in get_data
    dat.read(stream)
  File "C:\Users\TCclr\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\cobra-blender\pyffi_ext\formats\fgm\__init__.py", line 138, in read
    self.fgm_header.read(stream, data=self)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.82\python\lib\site-packages\pyffi\object_models\xml\struct_.py", line 373, in read
    attr_value.read(stream, data)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.82\python\lib\site-packages\pyffi\object_models\xml\array.py", line 303, in read
    elem.read(stream, data)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.82\python\lib\site-packages\pyffi\object_models\xml\struct_.py", line 373, in read
    attr_value.read(stream, data)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.82\python\lib\site-packages\pyffi\object_models\common.py", line 167, in read
    stream.read(self._size))[0]
struct.error: unpack requires a buffer of 4 bytes

location: <unknown location>:-1

**Comment by HENDRIX-ZT2** [comment]
Did you unpack the mdl2 afresh with the latest version of the tool?

**Comment by james-creator** [comment]
> Did you unpack the mdl2 afresh with the latest version of the tool?

doing that worked!, thank you so much!
